force-app/main/default/objects/DEL_RECON_Accelerator__c/DEL_RECON_Accelerator__c.object-meta.xml
<CustomObject>
    <description>RECON Accelerator</description>
    <label>RECON Accelerator</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>RECON Accelerator Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RECON Accelerator</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DEL_RECON_Accelerator__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DEL_RECON_AcceleratorRequest.cls
/**
* @author        Nancy Gupta / Apurva Agarwal 
* @date          16/06/2018
* @description   Class that handles the csv file upload and invokes the batch class to process it
* @name          DEL_RECON_AcceleratorRequestBatch 
*/

public class DEL_RECON_AcceleratorRequest{
    
    public Blob csvFileBody { get; set; }
    public String csvFileName { get; set; }
    public String csvNotSelectedError{ get; set; }
    public String csvNotSelectedSuccess{ get; set; }
    
    /*
    Method Name           : importCSVFile
    Method Description    : method reads a file that is selected by the user 
    						and invokes the batch method for further processing
    Input                 : NA
    Output                : PageReference             
    */
    public PageReference importCSVFile() {
        try{
            ID ReportID = ApexPages.currentPage().getParameters().get('id');
            if(csvFileBody!= Null){
                DEL_RECON_Accelerator__c rec = new DEL_RECON_Accelerator__c();
                rec.ID = ReportID;
                rec.Status__c = 'Submitted';
                if(rec != Null && rec.ID != Null){
                    update rec;
                }
                String csvBody = csvFileBody.toString();
                DEL_RECON_AcceleratorRequestBatch b = new DEL_RECON_AcceleratorRequestBatch(csvBody,ReportID,csvFileName); 
                Database.executebatch(b, 1);
                csvNotSelectedError ='';
                csvNotSelectedSuccess = 'Successfully uploaded. Please close the window.';
            }
            else{
                csvNotSelectedError = 'Please select a CSV file to proceed';
                csvNotSelectedSuccess = '';
            }
        }
        catch(exception e){
            csvNotSelectedError = e.getMessage();
        }
        return null;
    }
}