force-app/main/default/objects/DEL_RECON_Accelerator__c/DEL_RECON_Accelerator__c.object-meta.xml
<CustomObject>
    <description>RECON Accelerator</description>
    <label>RECON Accelerator</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>RECON Accelerator Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RECON Accelerator</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DEL_RECON_Accelerator__c/fields/Column_Number__c.field-meta.xml
<CustomField>
    <fullName>Column_Number__c</fullName>
    <description>Column Number in which query is placed</description>
    <inlineHelpText>Please enter the Column Number in which query is placed. Start count will be 1.</inlineHelpText>
    <label>Query Column Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DEL_RECON_AcceleratorRequest_Test.cls
/**
* @author        Nancy Gupta / Apurva Agarwal 
* @date          16/06/2018
* @description   Test Class for covering the classes related to Recon Accelerator
* @name          DEL_RECON_AcceleratorRequest_Test 
*/

@isTest
public class DEL_RECON_AcceleratorRequest_Test{
    @isTest(seeAllData=true)
    static void Recon_Accelerator_Method1(){
        
        Test.startTest();
        DEL_RECON_Accelerator__c reconAccrec = new DEL_RECON_Accelerator__c();
        reconAccrec.Column_Number__c = 2;
        insert reconAccrec;
        
        PageReference pageRef = Page.DEL_RECON_AcceleratorRequest;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', reconAccrec.id);
        
        DEL_RECON_AcceleratorRequest reconAcc = new DEL_RECON_AcceleratorRequest();
        reconAcc.csvFileBody = Blob.valueOf('');
        reconAcc.csvFileName = 'test.csv';
        reconAcc.importCSVFile();
        
        
        reconAcc.csvFileBody = Blob.valueOf('Grouping,FOCUS Salesforce/Extract Query\r\nFoundational Data,select count(id) from user');
        reconAcc.csvFileName = 'test2.csv';
        reconAcc.importCSVFile();
        
        Test.stopTest();
        
    }
    
}