force-app/main/default/objects/Schedule_Report__c/Schedule_Report__c.object-meta.xml
<CustomObject>
    <label>Scheduler</label>
    <nameField>
        <displayFormat>S R - {0000}</displayFormat>
        <label>S R</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduler</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_Report__c/fields/Email_Addresses__c.field-meta.xml
<CustomField>
    <fullName>Email_Addresses__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Addresses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schedule_Report__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Schedule_Report__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/schedule_report_Test.cls
@isTest
public class schedule_report_Test{
    private static testmethod void test_schedule(){
        Schedule_Report__c sch = new Schedule_Report__c();
        sch.Start_Date__c = System.now();
        sch.End_Date__c = system.now()+5;
        sch.Email_Addresses__c = 'achsharath@gmail.com , sharath@gmail.com';
        insert sch;
        
        schedule_report SR = new schedule_report();
        SR.create_Task(sch.Start_Date__c , sch.End_Date__c, sch.id );
        
    }
}