force-app/main/default/objects/Reports_Sceduled__c/Reports_Sceduled__c.object-meta.xml
<CustomObject>
    <label>Reports Sceduled</label>
    <nameField>
        <displayFormat>R S - {0000}</displayFormat>
        <label>R S</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reports Sceduled</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reports_Sceduled__c/fields/Report_Folder__c.field-meta.xml
<CustomField>
    <fullName>Report_Folder__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Report Folder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reports_Sceduled__c/fields/Report_Id__c.field-meta.xml
<CustomField>
    <fullName>Report_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Report Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reports_Sceduled__c/fields/Scheduler__c.field-meta.xml
<CustomField>
    <fullName>Scheduler__c</fullName>
    <label>Scheduler</label>
    <referenceTo>Schedule_Report__c</referenceTo>
    <relationshipLabel>Reports Sceduled</relationshipLabel>
    <relationshipName>Reports_Sceduled</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_Report__c/Schedule_Report__c.object-meta.xml
<CustomObject>
    <label>Scheduler</label>
    <nameField>
        <displayFormat>S R - {0000}</displayFormat>
        <label>S R</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduler</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_Report__c/fields/Email_Addresses__c.field-meta.xml
<CustomField>
    <fullName>Email_Addresses__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Addresses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schedule_Report__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Schedule_Report__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Report_Search_and_add_test.cls
@isTest
public class Report_Search_and_add_test{

    private static testmethod void test_search(){
        
        Schedule_Report__c sch = new Schedule_Report__c();
        sch.Start_Date__c = System.now();
        sch.End_Date__c = system.now()+5;
        sch.Email_Addresses__c = 'achsharath@gmail.com , sharath@gmail.com';
        insert sch;
        
        Reports_Sceduled__c rep_sch = new Reports_Sceduled__c();
        rep_sch.Report_Folder__c = 'Folder Name';
        rep_sch.Report_Id__c = 'a0hO00000041q7d';
        rep_sch.Report_Name__c = 'Report Name';
        rep_sch.Scheduler__c = sch.id;
        insert rep_sch;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(Sch);
        
        PageReference pageRef = Page.Schedule_report;
        pageRef.getParameters().put('id', String.valueOf(sch.Id));
        Test.setCurrentPage(pageRef);
        
        Report_Search_and_add RS = new Report_Search_and_add(sc);
        RS.selected_folder_name = 'Folder Name';
        RS.searchString = 'test';
        RS.getFolder_name();
        RS.update_available_report();
        RS.add_to_selected();
        RS.toSelect = rep_sch.id;
        RS.add_to_selected();
        RS.remove_selected();
        RS.rep_sch_id = rep_sch.id;
        RS.go_next();
        RS.onSave();
        RS.onCancel();
        
        RS.go_back();
        RS.save_new();
    }
}