force-app/main/default/objects/Reports_Sceduled__c/Reports_Sceduled__c.object-meta.xml
<CustomObject>
    <label>Reports Sceduled</label>
    <nameField>
        <displayFormat>R S - {0000}</displayFormat>
        <label>R S</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reports Sceduled</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Reports_Sceduled__c/fields/Report_Folder__c.field-meta.xml
<CustomField>
    <fullName>Report_Folder__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Report Folder</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reports_Sceduled__c/fields/Report_Id__c.field-meta.xml
<CustomField>
    <fullName>Report_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Report Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reports_Sceduled__c/fields/Scheduler__c.field-meta.xml
<CustomField>
    <fullName>Scheduler__c</fullName>
    <label>Scheduler</label>
    <referenceTo>Schedule_Report__c</referenceTo>
    <relationshipLabel>Reports Sceduled</relationshipLabel>
    <relationshipName>Reports_Sceduled</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_Report__c/Schedule_Report__c.object-meta.xml
<CustomObject>
    <label>Scheduler</label>
    <nameField>
        <displayFormat>S R - {0000}</displayFormat>
        <label>S R</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduler</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_Report__c/fields/Email_Addresses__c.field-meta.xml
<CustomField>
    <fullName>Email_Addresses__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Addresses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schedule_Report__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Schedule_Report__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Users_Receving__c/Users_Receving__c.object-meta.xml
<CustomObject>
    <label>Users Receiving</label>
    <nameField>
        <displayFormat>U R - {0000}</displayFormat>
        <label>Users Receving</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Users Receiving</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Users_Receving__c/fields/Scheduler__c.field-meta.xml
<CustomField>
    <fullName>Scheduler__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduler</label>
    <referenceTo>Schedule_Report__c</referenceTo>
    <relationshipLabel>Users Receiving</relationshipLabel>
    <relationshipName>Users_Receiving</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Users_Receving__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Users_Receiving</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Send_Daily_Report_test.cls
@isTest
Public class Send_Daily_Report_test{
    private static testmethod void test_mail(){
        
        List<User> u = [Select id,name from User];
        //List <Report> reportList = [SELECT Id,DeveloperName FROM Report Where FolderName = 'Daily_Report'];
        
        Schedule_Report__c sch = new Schedule_Report__c();
        sch.Start_Date__c = System.now();
        sch.End_Date__c = system.now()+5;
        sch.Email_Addresses__c = 'achsharath@gmail.com , sharath@gmail.com';
        insert sch;
        List<id> ids = new List<id>();
        ids.add(sch.id);
        
        Reports_Sceduled__c rep_sch = new Reports_Sceduled__c();
        rep_sch.Report_Folder__c = 'Folder Name';
        rep_sch.Report_Id__c = '00OO0000000gQWO';
        rep_sch.Report_Name__c = 'Report Name';
        rep_sch.Scheduler__c = sch.id;
        insert rep_sch;
        
        Reports_Sceduled__c rep_sch1 = new Reports_Sceduled__c();
        rep_sch1.Report_Folder__c = 'Folder Name';
        rep_sch1.Report_Id__c = '00OO0000000gQWO';
        rep_sch1.Report_Name__c = 'Report Name';
        rep_sch1.Scheduler__c = sch.id;
        insert rep_sch1;
        
        Users_Receving__c UR = new Users_Receving__c();
        UR.User__c = u[0].id;
        UR.Scheduler__c = sch.id;
        insert UR;
        
        Send_Daily_Report.schedule_report(ids);
        Send_Daily_Report.test_method();
    }
}