force-app/main/default/objects/Quote_Line__c/Quote_Line__c.object-meta.xml
<CustomObject>
    <label>Quote Line</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line__c/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Quote Line</relationshipLabel>
    <relationshipName>Quote_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Submit_Approval_ButtonClass.cls
global with sharing class Submit_Approval_ButtonClass {
    webservice static string Apr_Submit(String parentid){
        Quote_Line__c LI = [Select id,name from Quote_Line__c WHERE Quote_Line_Item__c =: parentid];
        
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setComments('Send Record for Approval');
        req.setObjectId(LI.Id);
        req.setSubmitterId(UserInfo.getUserId());
        
        Approval.ProcessResult Result = Approval.process(req);
        return null;
    }
}