force-app/main/default/objects/Search_Setting__c/Search_Setting__c.object-meta.xml
<CustomObject>
    <label>Search Setting</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Search_Setting__c/fields/Fields_To_Display__c.field-meta.xml
<CustomField>
    <fullName>Fields_To_Display__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Please Enter Field APIs with Comma Separated</inlineHelpText>
    <label>Fields To Display</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Search_Setting__c/fields/Filter_Fields__c.field-meta.xml
<CustomField>
    <fullName>Filter_Fields__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Filter Fields</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
public class TestDataFactory {
    public static Account createAccount(string Name, string type, string Industry){
        Account acc = new Account();
        acc.Name = Name;
        acc.Type = type;
        acc.Industry = Industry;
        insert acc;
        return acc;
    }
    
    public static contact createContact(id accountId, string firstName, string lastName, string email){
        Contact con = new Contact();
        con.AccountId = accountId;
        con.FirstName = firstName;
        con.LastName = lastName;
        con.Email = email;
        return con;
    }
    
    public static Search_Setting__c createSS(string name, string FTD, string FF){
        Search_Setting__c ss = new search_setting__c();
        ss.Name = name;
        ss.Fields_To_Display__c = FTD;
        ss.Filter_Fields__c = FF;
        insert ss;
        return ss;
    }
}