force-app/main/default/objects/Metadata__c/Metadata__c.object-meta.xml
<CustomObject>
    <label>Metadata</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metadata</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Metadata__c/fields/Change_Summary__c.field-meta.xml
<CustomField>
    <fullName>Change_Summary__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Change Summary</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Metadata__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Metadata</relationshipLabel>
    <relationshipName>Metadata</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>US</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/userStorySummary.cls
public with sharing class userStorySummary {
    public userStorySummary() {

    }
    @AuraEnabled(cacheable=false)
    public static string metadataSummary(string recId){
        string summary='';
        for(Metadata__c md : [SELECT id,Name,Change_Summary__c FROM Metadata__c WHERE User_Story__c =: recId]){
            summary = summary+md.Change_Summary__c+'\n\n';
        }
        system.debug('Summary----'+summary);
        string htmlContent= markdownDataConverter.markdownHtml(summary);
        return htmlContent;
    }

}